
services:

  request-service:
    container_name : request-service
    build:
      context: .
      dockerfile: ./request-service/Dockerfile
    ports:
        - "8080:8080"
    environment:
      DB_HOST: db
      DB_PORT: 5432
      DB_USER: admin
      DB_PASSWORD: admin
      DB_NAME: cosc349_database

